### ISSUE TITLE
cat_vs_roomba missing "resources/cat_mouse.mod"

### ISSUE THREAD

**Issue by wlxmhls** [raysan5/raylib-games#13]
Hello,  there is no asset file "resources/cat_mouse.mod" in the "cat_vs_roomba", which is loaded in source file "cat_vs_roomba.c", line 75:
`music = LoadMusicStream("resources/cat_mouse.mod");`

ADDITIONAL:
No "catch22.mod" found in resource folder, corresponding "screen_gameplay.c", line 309:
`catch = LoadMusicStream("resources/catch22.mod");`

**Comment by wlxmhls** [comment]
PLEASE...

**Comment by raysan5** [comment]
@wlxmhls I'm afraid I have no idea where are those files, sorry.
