### ISSUE TITLE
Seems like SetMusicVolume sets things in other part of the memory

### ISSUE THREAD

**Issue by VitalZero** [raysan5/raylib-games#8]
Hi!, I'm writing a tetris like game, I build a board (board class) filled with white tiles on the left, right and bottom edges, and black on the rest. I Just started to use Music Streams, I load, play and unload the music stream on the game class, the loading occurs in the game constructor, the play occurs on the run function, before the game loop, the update occurs after the drawing inside the game loop, and unload occurs after exiting the game loop in the run function.
Now, everything goes fine until I use the function SetMusicvolume(music, 0.8f); just after the PlayMusicvolume(music);, on which, the tiles the are supposed to be black, are drawn dark blue. Already checked the debbuger and the color stays on black {0, 0, 0, 255} but its being drawn dark blue. Now, the board class is on its own header and source file, separated from game class file. the value of the black tiles (which is -1, the value is not changed, checked on the debbuger). Can you help me please? Thank you!

**Comment by raysan5** [comment]
I reviewed `SetMusicVolume()` and it doesn't seem to be leaking any memory or accessing any invalid memory point. Please, could you provide a **minimal code example** illustrating your problem?

**Comment by VitalZero** [comment]
Sure, you can find the complete source code here tho: https://github.com/VitalZero/Tetris-raylib

Code:

Game:
#include <iostream>
#include <raylib.h>

Game::Game(int width, int height)
	:
	board(0, 0, Board::TileSize), mino(0, 0, Mino::Shape::S, Board::TileSize, board)
{
	InitWindow(width, height, "Tetris raylib!");
	InitAudioDevice();
	music = LoadMusicStream("badguyinst.mp3");
}

void Game::Run()
{
	PlayMusicStream(music);
	//SetMusicVolume(music, 0.8f);

	while (!WindowShouldClose())
	{
		Input();
		Update(GetFrameTime());

		BeginDrawing();
		ClearBackground(BLACK);
		Draw();
		EndDrawing();

		UpdateMusicStream(music);
	}

	StopMusicStream(music);
	UnloadMusicStream(music);
	CloseAudioDevice();
	CloseWindow();
}
void Game::Draw()
{
	board.Draw();

	DrawText("Tetris raylib!", 390, 30, 20, RAYWHITE);
	DrawText("Score: 000000", 390, 60, 20, RAYWHITE);
	DrawText("Next", 390, 90, 30, RAYWHITE);
}

Board:

#pragma once

class Board
{
public:
	Board(int x, int y, int tileSize);
	void Draw()

public:
	static constexpr int TileSize = 30;

private:
	int lineFilled = -1;
	static constexpr int tilesWidth = 12;
	static constexpr int tilesHeight = 20;
	int map[tilesHeight * tilesWidth] =
	{
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
		9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 9,
	};
};

Cpp

#include "Board.h"
#include <raylib.h>
#include "Mino.h"

Board::Board(int x, int y, int tileSize)
{
}

void Board::Draw()
{
	for (int y = 0; y < tilesHeight; ++y)
	{
		for (int x = 0; x < tilesWidth; ++x)
		{
			int tileData = TileAt(x, y);

			Color color = RAYWHITE;

			if (tileData == -1)
				color = BLACK;
			if (tileData == 9)
				color = RAYWHITE;
			else
				color = Mino::colors[TileAt(x, y)];

			DrawRectangle(x * TileSize + 1, y * TileSize + 1, TileSize - 1, TileSize - 1, color);
		}
	}
}

**Comment by raysan5** [comment]
@VitalZero Please, could you provide a simple C example illustrating the issue instead of a C++ one?

**Comment by VitalZero** [comment]
> @VitalZero Please, could you provide a simple C example illustrating the issue instead of a C++ one?

Sure!
This is it, very minimal, doesn't do it here tho :/ 

```
#include <raylib.h>

// colors
Color colors[7] = {
	BLUE,
	DARKBLUE,
	DARKGRAY,
	DARKGREEN,
	PURPLE,
	YELLOW,
	RED
};

// board stuff
static int board[12 * 20] = {
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9,
	9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
};

void DrawBoard();
int TileAt(int board[12 * 20], int x, int y);

// game loop stuff
void Input();
void Update(float dt);
void Draw();

int main()
{
	Music music = { 0 };
	InitWindow(600, 800, "test");
	InitAudioDevice();
	music = LoadMusicStream("putyourmp3here.mp3");

	PlayMusicStream(music);
	SetMusicVolume(music, 0.8f);

	while (!WindowShouldClose())
	{
		Input();
		Update(GetFrameTime());

		BeginDrawing();
		ClearBackground(BLACK);
		Draw();
		EndDrawing();

		UpdateMusicStream(music);
	}

	StopMusicStream(music);
	UnloadMusicStream(music);
	CloseAudioDevice();
	CloseWindow();

	return 0;
}

void DrawBoard()
{
	for (int y = 0; y < 20; ++y)
	{
		for (int x = 0; x < 12; ++x)
		{
			int tileData = TileAt(board, x, y);
			Color tileColor = RAYWHITE;

			if (tileData == -1)
				tileColor = BLACK;
			if (tileData == 9)
				tileColor = RAYWHITE;
			else
				tileColor = colors[TileAt(board, x, y)];

			DrawRectangle(x * 30 + 1, y * 30 + 1, 30 - 1, 30 - 1, tileColor);
		}
	}
}

int TileAt(int b[12 * 20], int x, int y)
{
	return b[y * 12 + x];
}

void Input()
{
	// empty
}

void Update(float dt)
{
	// empty
}

void Draw()
{
	DrawBoard();
}

```
